#!/bin/bash

read_spec() {
  cat spec.json
}

if [ $# -ne 0 -a $# -ne 1 ]; then
  echo 'Usage: ./download [base_game]' >&2
  exit 1
fi

mkdir tmp
trap "rm -r tmp" EXIT

DEST="downloaded_games"
if [ ! -d "$DEST" ]; then
  mkdir "$DEST"
fi

count=$(read_spec | jq length)
for i in $(seq 0 $((count-1)))
do
  item="$(read_spec | jq ".[$i]")"
  name=$(echo "$item" | jq -r .name)
  variantOf=$(echo "$item" | jq -r .variant_of)

  if [ $# -eq 1 -a "$name" != "$1" ]; then
    echo "Skipping $name."
    continue
  fi

  if [ "$variantOf" != "null" ]; then
    echo "Skipping variant $name of $variantOf."
    continue
  fi

  baseURL="$(echo "$item" | jq -r .base)"

  if [ -d "$DEST/$name" ]; then
    echo "Already have $name."
    continue
  fi

  echo "Downloading $name ..."

  dldir="tmp/$name"
  mkdir "$dldir"
  echo "$item" > "$dldir/info.json"
  curl -s "$baseURL" > "$dldir/index.html" || continue

  for resource in $(echo "$item" | jq -r '.resources | .[]')
  do
    mkdir -p "$(dirname "$dldir/$resource")"
    curl -s "$baseURL$resource" > "$dldir/$resource" || continue 2
  done

  # Run site-specific processing scripts.
  for proc in $(echo "$item" | jq -r '.processors | .[]')
  do
    ./process/$proc "$dldir" || continue 2
  done

  # Build up two JavaScript files to inject.
  for place in top bottom
  do
    inject_file="$dldir/muniverse_${place}_injections.js"
    touch "$inject_file"
    for injection in $(echo "$item" | jq -r ".${place}_injections | .[]")
    do
      cat "injections/$injection" >> "$inject_file"
    done
  done

  # Inject JavaScript files at top & bottom of <head>.
  mv "$dldir/index.html" "$dldir/index_pre_inject.html"
  cat "$dldir/index_pre_inject.html" |
    sed -E 's/(<head>)/\1<script src="muniverse_top_injections.js"><\/script>/g' |
    sed -E 's/(<\/head>)/<script src="muniverse_bottom_injections.js"><\/script>\1/g' \
    > "$dldir/index.html"

  mv "$dldir" "$DEST"
  echo "Successfully downloaded $name"
done
