#!/bin/bash

DIR="$1"

mv "$DIR/index.html" "$DIR/index_pre_4j_c2game.html"
cat "$DIR/index_pre_4j_c2game.html" |
  sed -E 's/\/\/h5\.4j\.com\/forgame\/css\/game\.css/game.css/g' |
  sed -E 's/\/\/h5\.4j\.com\/forgame\/js\/jquery-2.1.1.min.js/jquery.js/g' |
  sed -E 's/<script src="\/\/.*<\/script>//g' \
  > "$DIR/index.html"

curl -s 'https://h5.4j.com/forgame/js/jquery-2.1.1.min.js' \
  > "$DIR/jquery.js" || exit 1
curl -s 'https://h5.4j.com/forgame/js/com4japi.min.v1.9.5.js' \
  > "$DIR/com4j.js" || exit 1
curl -s 'https://h5.4j.com/forgame/css/game.css' \
  > "$DIR/game.css" || exit 1
