#!/bin/bash

DIR="$1"

# Manually include script.
mv "$DIR/index.html" "$DIR/index_pre_burninrubber.html"
cat "$DIR/index_pre_burninrubber.html" |
  sed -E "s/'js\\/all.js',//g" |
  sed -E 's/(<\/body>)/<script src="js\/all\.js"><\/script>\1/g' \
  > "$DIR/index.html"
