#!/bin/bash

DIR="$1"

# Format famobi_gameJS properly.
mv "$DIR/index.html" "$DIR/index_pre_colorpop.html"
cat "$DIR/index_pre_colorpop.html" |
  sed -E "s/'js\\/all\\.js',//g" |
  sed -E 's/navigator\.serviceWorker\.register\(/\/\//g' |
  sed -E 's/(<\/body>)/<script src="js\/all\.js"><\/script>\1/g' \
  > "$DIR/index.html"
