#!/bin/bash

if [ $# -ne 1 ]; then
  echo 'Usage: famobi <directory>' >&2
  exit 1
fi

DIR="$1"

if [ ! -f "$DIR/index.html" ]; then
  echo 'No index.html file' >&2
  exit 1
fi

# Download Famobi API data (e.g. localized strings).
famid="$(cat "$DIR/info.json" | jq -r '.metadata.famobi_id')"
pageData="$(curl -s "https://play.famobi.com/$famid" || exit 1)"
playURL=$(echo "$pageData" | grep 'href="https://games.cdn.famobi.com/html5games' |
          sed -E $'s/[ \t]*<a href="//g' |
          sed -E 's/">.*//g')
fgPID=$(echo "$playURL" | sed -E 's/.*fg_pid=([0-9A-Za-z\-]*).*/\1/g')
fgUID=$(echo "$playURL" | sed -E 's/.*fg_uid=([0-9A-Za-z\-]*).*/\1/g')
escapedURL=$(echo "$playURL" |
          sed -E 's/&/%26/g' |
          sed -E 's/:/%3A/g' |
          sed -E 's/\//%2F/g' |
          sed -E 's/\?/%3F/g')
scriptBase='http://api.famobi.com/gameapi/script'
fgScriptURL=$(echo "$scriptBase/$fgUID/$fgPID?_location=$escapedURL")
fgScript=$(curl -s "$fgScriptURL" || exit 1)
echo "$fgScript" | grep -E '(new fg_api|{"features")' > "$DIR/famobi_data.js"

# Strip the code that normally loads all the scripts,
# opting to manually load the scripts instead.
mv "$DIR/index.html" "$DIR/index_pre_famobi.html"
cat "$DIR/index_pre_famobi.html" |
  sed -E "s/\\(document, '\\/html5games\\/gameapi\\/v1\\.js\\?e='\\)//g" |
  sed -E $'s/^[ \t]*"(js\\/.*.js)",/<script src="\\1"><\\/script>/g' |
  sed -E 's/window.famobi_gameJS = \[/<\/script>/g' |
  sed -E 's/(function\(\)\{)/<script> window.addEventListener("load",\1/g' |
  sed -E 's/        \];/);/g' |
  sed -E 's/<head>/<head><script src="famobi_data.js"><\/script>/g' \
  >"$DIR/index.html"
