#!/bin/bash

DIR="$1"

mv "$DIR/index.html" "$DIR/index_pre_fititquick.html"
cat "$DIR/index_pre_fititquick.html" |
  sed -E "s/'js\\/all\\.js',//g" |
  sed -E 's/(<\/body>)/<script src="js\/all\.js"><\/script>\1/g' \
  > "$DIR/index.html"

# Remove google analytics.
mv "$DIR/js/all.js" "$DIR/js/all.preproc.js"
cat "$DIR/js/all.preproc.js" |
  sed -E 's/,function\(e,a,t,s,i,l,o\)\{e\.Google.*ga\("send","pageview"\)//g' \
  > "$DIR/js/all.js"
