#!/bin/bash

DIR="$1"

# Format famobi_gameJS properly.
mv "$DIR/index.html" "$DIR/index_pre_fitzcolor.html"
cat "$DIR/index_pre_fitzcolor.html" |
  tail -c +4 |
  sed -E $'s/"dist\\/all\\.js",/\\\n/g' |
  sed -E $'s/\\}\\];/\\}\\\n \\];/g' |
  sed -E 's/(<\/body>)/<script src="dist\/all\.js"><\/script>\1/g' \
  > "$DIR/index.html"
