#!/bin/bash

DIR="$1"

cp "$DIR/gfx_preloader/fruit0.png" "$DIR/dummy_image.png"

# Format famobi_gameJS properly.
mv "$DIR/index.html" "$DIR/index_pre_fruitpulp.html"
cat "$DIR/index_pre_fruitpulp.html" |
  sed -E "s/'js\\/all\\.js',//g" |
  sed -E 's/(<\/body>)/<script src="js\/all\.js"><\/script>\1/g' \
  > "$DIR/index.html"
