#!/bin/bash

DIR="$1"

# Format famobi_gameJS properly.
mv "$DIR/index.html" "$DIR/index_pre_uforun.html"
cat "$DIR/index_pre_uforun.html" |
  sed -E $'s/\'(js\\/all\\.js)\\\',/\\\n/g' |
  sed -E 's/(<\/body>)/<script src="js\/all\.js"><\/script>\1/g' \
  > "$DIR/index.html"
