#!/bin/bash

DIR="$1"

mkdir "$DIR/js" "$DIR/css"
for asset in js/jquery-1.4.2.min.js js/dynamicaudio-0.2.min.js css/style.css \
             js/jsnes-37cb0ecea5bc768a4899a1403d6335f5b0dbaa35.js
do
  curl -s https://fir.sh/$asset > "$DIR/$asset"
done

# Strip external APIs and insert a JS hook.
mv "$DIR/index.html" "$DIR/index_pre_jsnes.html"
cat "$DIR/index_pre_jsnes.html" |
  sed -E 's/((src|href)=")\//\1/g' |
  sed -E 's/\}\)\(\);/})/g' |
  sed -E "s/\\(document, 'script', 'facebook-jssdk'\\)//g" |
  sed -E 's/.*platform\.twitter\.com.*//g' |
  sed -E 's/.*typekit\.com.*//g' |
  sed -E 's/(new JSNES)/window.globalJSNES = \1/g' \
  > "$DIR/index.html"
