#!/bin/bash

DIR="$1"

# Format famobi_gameJS properly.
mv "$DIR/index.html" "$DIR/index_pre_kittybubbles.html"
cat "$DIR/index_pre_kittybubbles.html" |
  sed -E $'s/\'js\\/all\\.js\',/\\\n/g' |
  sed -E $'s/\\}\\];/\\}\\\n \\];/g' |
  sed -E 's/(<\/body>)/<script src="js\/all\.js"><\/script>\1/g' \
  > "$DIR/index.html"

# Inject a hook into the game.
mv "$DIR/js/all.js" "$DIR/js/all.preproc.js"
cat "$DIR/js/all.preproc.js" |
  sed -E 's/(pauseGame:function\(\)\{)/\1return;/g' |
  sed -E 's/(var o=function\(\)\{var t=this;)/\1window.globalAppObject=this;/g' \
  > "$DIR/js/all.js"
