#!/bin/bash

DIR="$1"

# Format famobi_gameJS properly.
mv "$DIR/index.html" "$DIR/index_pre_multisquare.html"
cat "$DIR/index_pre_multisquare.html" |
  sed -E $'s/\'js\\/all\\.js\',/\\\n/g' |
  sed -E $'s/\\}\\];/\\}\\\n \\];/g' |
  sed -E 's/(<\/body>)/<script src="js\/all\.js"><\/script>\1/g' \
  > "$DIR/index.html"

# Hook into JS.
mv "$DIR/js/all.js" "$DIR/js/all.preproc.js"
cat "$DIR/js/all.preproc.js" |
  sed -E 's/(this\.best=0)/window.globalMain=this;\1/g' \
  > "$DIR/js/all.js"
