#!/bin/bash

DIR="$1"

mv "$DIR/media/button%20tap_03.ogg" "$DIR/media/button tap_03.ogg"

# Format famobi_gameJS properly.
mv "$DIR/index.html" "$DIR/index_pre_penguinskip.html"
cat "$DIR/index_pre_penguinskip.html" |
  sed -E "s/'(js\\/all\\.js)\\',//g" |
  sed -E $'s/^( |\t)*\\}\\];/  \\}\\\n ];/g' |
  sed -E 's/(<\/body>)/<script src="js\/all\.js"><\/script>\1/g' \
  > "$DIR/index.html"
