#!/bin/bash

DIR="$1"

# Format famobi_gameJS properly.
mv "$DIR/index.html" "$DIR/index_pre_shards.html"
cat "$DIR/index_pre_shards.html" |
  sed -E "s/'(js\\/all\\.js)\\',//g" |
  sed -E 's/(<\/body>)/<script src="js\/all\.js"><\/script>\1/g' \
  > "$DIR/index.html"

# Insert hook into JS and fix orientation bug.
mv "$DIR/js/all.js" "$DIR/js/all.preproc.js"
cat "$DIR/js/all.preproc.js" |
  sed -E 's/e.isLandscape:e.isPortrait/true:true/g' |
  sed -E 's/(i\.Game=function\(t,e,s,n,o,r,a,h\)\{)/\1globalGameObj=this;/g' \
  > "$DIR/js/all.js"
