#!/bin/bash

DIR="$1"

# Format famobi_gameJS properly.
mv "$DIR/index.html" "$DIR/index_pre_soccergirl.html"
cat "$DIR/index_pre_soccergirl.html" |
  sed -E "s/'js\\/all\\.js',//g" |
  sed -E 's/(<\/body>)/<script src="js\/all\.js"><\/script>\1/g' \
  > "$DIR/index.html"

# Inject hook into JS.
mv "$DIR/js/all.js" "$DIR/js/all.preproc.js"
cat "$DIR/js/all.preproc.js" |
  sed -E 's/(openfl_Lib.current.stage.window.__fullscreen)/window.openfl_Lib=openfl_Lib;\1/g' |
  sed -E 's/n\.main\.addChild\(new PauseMenu\)/false/g' \
  > "$DIR/js/all.js"
