#!/bin/bash

DIR="$1"

oldName="$DIR/js/all_preprocess.js"
mv "$DIR/js/all.js" "$oldName"
cat "$oldName" |
  sed -E 's/^loadPreAssets\(\);/window\.addEventListener\("load",loadPreAssets\);/g' \
  > "$DIR/js/all.js"

oldName="$DIR/index_pre_streetpursuit.html"
mv "$DIR/index.html" "$oldName"
cat "$oldName" |
  sed -E "s/'js\/all\.js',//g" |
  sed -E 's/(<\/body>)/<script src="js\/all\.js"><\/script>\1/g' \
  > "$DIR/index.html"
