#!/bin/bash

DIR="$1"

# Remove ads and service worker.
mv "$DIR/index.html" "$DIR/index_pre_valto.html"
cat "$DIR/index_pre_valto.html" |
  sed -E 's/<div style="display:none;">.*(<\/body>)/\1/g' |
  sed -E 's/navigator\.serviceWorker\.register\(/\/\//g' \
  > "$DIR/index.html"

# Remove reference external JS file.
mv "$DIR/data.js" "$DIR/data.preproc.js"
cat "$DIR/data.preproc.js" |
  sed -E 's/\/\/www.yiv.com\/js\/GameApi\.js//g' \
  > "$DIR/data.js"
